# Generated by Django 5.1.3 on 2024-12-02 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('unique_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('detailed_analysis', models.JSONField(blank=True, null=True)),
                ('visualization', models.JSONField(blank=True, null=True)),
                ('feedback_quotes', models.JSONField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats',
                'constraints': [models.UniqueConstraint(fields=('user', 'unique_uuid'), name='unique_chat_id_per_user')],
            },
        ),
    ]
