# Generated by Django 5.1.3 on 2024-12-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from api.accounts.models import TIMEZONES_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timezone', models.CharField(choices=TIMEZONES_CHOICES, default='UTC', max_length=50)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
